sonar.projectKey=Crysta1221_pyexample
sonar.organization=crysta1221
sonar.sources=pyexample
sonar.tests=tests
sonar.exclusions=.venv/**,.tox/**
sonar.coverage.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml